[project]
name = "braid-opto-arena"
version = "0.1.0"
description = "A program to run and control the opto arena"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gitpython>=3.1.43",
    "matplotlib>=3.9.3",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "pre-commit>=4.0.1",
    "pygame>=2.6.1",
    "pyqtgraph>=0.13.7",
    "pyserial>=3.5",
    "pyzmq>=26.2.0",
    "requests>=2.32.3",
    "ruff>=0.8.2",
    "scikit-learn>=1.5.2",
    "scipy>=1.14.1",
    "tqdm>=4.67.1",
]
